/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learning_java11;
import helloworld.HelloWorldApp;
public class App extends  HelloWorldApp {
    public String getGreeting() {
        var app = new HelloWorldApp();
        return app.getMessage();
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
